# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LEChromeProgressViewDemo' do
  # use_frameworks!

  pod 'LEChromeProgressView' , :path => '../'

end
